export default Object.freeze({
    ACCOUNT: "Account",
    ACCOUNT_INFO: "AccountInfo",
    CART: "Cart",
    HOME: 'Home',
    LOGIN: "Login",
    REGISTER: "Register",
    WISH_LIST: "Wishlist",
    PRODUCT_LIST: "ProductList",
    PRODUCT_DETAILS: 'ProductDetail',
    SPOTLIGHT_PRODUCT_LIST: "SpotLightProductList",
    FORGET_PASSWORD: "forgetPassword",
    CATEGORY_LIST: "CategoryList",
    CURRENT_DELIVERY: "CurrentDelivery",
    ACCEPTNEWDELIVERY: "AcceptDelivery",
    VAHAN: "VerifyVahan",
    SARTHI: "VerifySarthi",
    DeliveryDetails: "DeliveryDetails",
    History : "History"
})